service: caption-backend

provider:
  name: aws
  runtime: python3.12
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:ListBucket
          Resource: 
            - "arn:aws:s3:::hyper-editor/*"
            - "arn:aws:s3:::hyper-editor"
  environment:
    BUCKET_NAME: hyper-editor
    PYTHONPATH: "./"

functions:
  processVideo:
    handler: backend.lambda_handler.lambda_handler
    timeout: 900  # 15 minutes
    memorySize: 10240  # 10GB
    events:
      - http:
          path: process
          method: post
          cors: true
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p312-ffmpeg:1

package:
  patterns:
    - "!node_modules/**"
    - "!venv/**"
    - "!__pycache__/**"
    - "!.git/**"
    - "!.serverless/**"
    - "!.gitignore"
    - "!README.md"
    - "!requirements.txt"
    - "!serverless.yml"
    - "!remotion/**"
  individually: true
  excludeDevDependencies: false

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
    slim: true
    noDeploy:
      - boto3
      - botocore 